# Generated by Django 5.0.3 on 2024-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipepost_reciple_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='reciple_label',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='recipe_label',
            field=models.CharField(choices=[('BEGGINERS', 'BEGGINERS'), ('INTERMEDIATE', 'INTERMEDIATE'), ('EXPERT', 'eXPERT')], default='BEGGINERS', max_length=30),
        ),
    ]
