# Generated by Django 5.0.3 on 2024-04-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipepost_is_best_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='recipe_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.category'),
            preserve_default=False,
        ),
    ]
